In [2]:
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

In [1]:
#Generally Important libraries
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Libraries for Gridsearch
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

#Libraries for PCA
from sklearn.decomposition import PCA

#Libraries imported for the Decision Tree Part
from sklearn.tree import DecisionTreeClassifier, plot_tree

#Libraries imported for the Random forest part
from sklearn.ensemble import RandomForestClassifier

#Libraries for SVC
from sklearn.svm import SVC

#Libraries for MLP
from sklearn.neural_network import MLPClassifier

#Keras libraries for Neural Networks
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Dropout
from keras import optimizers, initializers
from keras.layers.convolutional import Conv2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical
from keras.wrappers.scikit_learn import KerasClassifier

In [3]:
# TODO:
# 1. remove sparse data
# 2. Graph everything
# 3. Comments and analysis
# 4. Test different classifiers?
# 5. ACCURACY! 95 minimum

In [4]:
np.load('G_3_ant.npy').shape, np.load('G_3_grapes.npy').shape

((1000, 784), (1000, 784))

We have 1000 image of 28*28 size = 784.

We have p=784 features.

In [5]:
X_ant = np.load('G_3_ant.npy')
n_ant = X_ant.shape[0]
y_ant = np.ones(n_ant)
X_grapes = np.load('G_3_grapes.npy')
n_grapes = X_ant.shape[0]
y_grapes = -1 * np.ones(n_grapes)
X = np.vstack([X_ant, X_grapes])
y = np.hstack([y_ant, y_grapes])
X, y = shuffle(X, y, random_state=1)
X = X / 255.
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=1)

In [6]:
clf = SVC(kernel="linear")
clf.fit(X_train, y_train)
score = clf.score(X_test, y_test)
print("test score:", score)
grid = {'C' : np.logspace(0, 6, 7),
        'gamma' : np.linspace(0.001,0.01,11),
        'kernel':['poly', 'rbf']
       }
clf = GridSearchCV(estimator = SVC(), param_grid = grid, n_jobs=-1, verbose=2)
clf.fit(X,y)
print(clf.best_score_)
print(clf.best_params_)

Fitting the classifier to the training set
test score: 0.756
Fitting 5 folds for each of 154 candidates, totalling 770 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   24.7s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  4.5min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  8.3min
[Parallel(n_jobs=-1)]: Done 770 out of 770 | elapsed: 10.1min finished


0.875
{'C': 10.0, 'gamma': 0.001, 'kernel': 'rbf'}


In [14]:
print("Fitting the classifier to the training set")
clf = SVC(kernel="linear", C=0.001)
clf.fit(X_train, y_train)

score = clf.score(X_test, y_test)
print("Test score:", score)

Fitting the classifier to the training set
Test score: 0.842


In [75]:
pca = PCA(n_components=32)
X_PCA_train = pca.fit_transform(X_train)
X_PCA_test = pca.transform(X_test)
clf = SVC(kernel="rbf", C=14, gamma=0.001)#'scale')
clf.fit(X_PCA_train, y_train)
train_score = clf.score(X_PCA_train, y_train) 
test_score = clf.score(X_PCA_test, y_test)
print(confusion_matrix(y_test, clf.predict(X_PCA_test)))
train_score, test_score

[[206  23]
 [ 19 252]]


(0.9593333333333334, 0.916)

In [138]:
pca = PCA(n_components=32, random_state=10)
X_PCA_train = pca.fit_transform(X_train)
X_PCA_test = pca.transform(X_test)
clf = SVC(kernel="rbf", C=11, gamma='scale')
clf.fit(X_PCA_train, y_train)
train_score = clf.score(X_PCA_train, y_train) 
test_score = clf.score(X_PCA_test, y_test)
print(confusion_matrix(y_test, clf.predict(X_PCA_test)))
train_score, test_score

[[209  20]
 [ 21 250]]


(0.9926666666666667, 0.918)

In [122]:
clf.score(X_train, y_train)

ValueError: X.shape[1] = 784 should be equal to 32, the number of features at training time

In [49]:
pol = SVC(kernel="poly", C=1000000, gamma=0.01, degree=3)
pol.fit(X_train, y_train)
train_score = pol.score(X_train, y_train) 
test_score = pol.score(X_test, y_test)
train_score, test_score

(1.0, 0.874)

In [43]:
clf = SVC(kernel="rbf", C=10, gamma=0.01)#'scale')
sfs = SequentialFeatureSelector(clf, n_features_to_select=30)
sfs.fit(X_train, y_train)

train_score = sfs.score(X_train, y_train) 
test_score = sfs.score(X_test, y_test)
print(confusion_matrix(y_test, sfs.predict(X_test)))
train_score, test_score

NameError: name 'SequentialFeatureSelector' is not defined

In [44]:
model = SelectFromModel(clf, prefit=True)
X_train_new = model.transform(X_train)
X_test_new = model.transform(X_test)


ValueError: The underlying estimator SVC has no `coef_` or `feature_importances_` attribute. Either pass a fitted estimator to SelectFromModel or call fit before calling transform.

In [56]:
for i in range(784):
    print(sum(abs(X.T[i])))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
116.08410113843281
192.56446403612756
233.1329517260497
372.41837062244247
498.0166480826465
553.587930943828
649.7354566077736
703.1313348642916
768.5151573747917
829.0032639296237
911.4231608643553
943.616051357324
1000.0807923059334
1014.5923221843428
1020.7763266513911
976.6058122970758
933.8379081576352
870.1869505923703
830.5325031224929
786.1270853549755
722.6528689377259
630.4710296301578
505.4231277572875
437.99123947731755
301.265245990404
156.12924822344067
0.0
0.0
207.38533304654374
329.85340713753743
453.64312911445245
602.5161157293845
728.451421657525
836.3654474254272
911.8164154367214
985.2803974662932
1035.9704903626512
1108.4525145458147
1166.487315851291
1243.6767881517467
1271.913438714071
1299.904980231998
1313.6195897593366
1296.8149870449226
1231.124575957381
1177.9752051181865
1151.5931965403104
1084.9483301806342
1007.3357413143466
870.0702772425

In [73]:
import pandas as pd
df_describe = pd.DataFrame(X)
df_describe.describe()

0       1       2       3       4       5       6       7       8    \
count  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0   
mean      0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

          9    ...     774     775     776     777     778     779     780  \
count  2000.0  ...  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0  2000.0   
mean      0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
std       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
min       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
25%       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
50%       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
75%       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
max       0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

          781     782     783  
count  2000.0  2000.0  2000.0  
mean      0.0     0.0     0.0  
std       0.0     0.0     0.0  
min       0.0     0.0     0.0  
25%       0.0     0.0     0.0  
50%       0.0     0.0     0.0  
75%       0.0     0.0     0.0  
max       0.0     0.0     0.0  

[8 rows x 784 columns]

In [49]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
# DECISION TREE 
max_depth = 6
clf = DecisionTreeClassifier(max_depth=max_depth).fit(X_train, y_train)
train_score = clf.score(X_train, y_train) 
test_score = clf.score(X_test, y_test)
print(confusion_matrix(y_test, clf.predict(X_test)))
train_score, test_score

[[158  71]
 [ 55 216]]


(0.918, 0.748)

In [50]:
# DECISION TREE WITH PCA
max_depth = 6
n_components = 30

pca = PCA(n_components=n_components)
X_PCA_train = pca.fit_transform(X_train)
X_PCA_test = pca.transform(X_test)
clf = DecisionTreeClassifier(max_depth=max_depth).fit(X_PCA_train, y_train)
train_score = clf.score(X_PCA_train, y_train) 
test_score = clf.score(X_PCA_test, y_test)
print(confusion_matrix(y_test, clf.predict(X_PCA_test)))
train_score, test_score

[[182  47]
 [ 41 230]]


(0.9346666666666666, 0.824)

## Neural

In [2]:
eps = 15

X_ant = np.load('G_3_ant.npy')
n_ant = X_ant.shape[0]
y_ant = np.ones(n_ant)
X_grapes = np.load('G_3_grapes.npy')
n_grapes = X_ant.shape[0]
y_grapes = np.zeros(n_grapes)
X_raw = np.vstack([X_ant, X_grapes])
y = np.hstack([y_ant, y_grapes])
X, y = shuffle(X_raw, y, random_state=None)
X[np.where(X<eps)] = 0  # ignore little points, small pixels
X = X / 255.
X = StandardScaler().fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33)

In [3]:
def cnn_model():
    # create model
    model = Sequential()
    
    model.add(Conv2D(30, (5, 5), input_shape=s[1:], activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    
    model.add(Conv2D(15, (3, 3), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    
    model.add(Dropout(0.2))
    model.add(Flatten())
    
    model.add(Dense(128, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(num_classes, activation='softmax'))
    
    # Compile model
    opt = optimizers.Adam(lr=0.0004, decay=1e-6)
    model.compile(loss='categorical_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])
    return model

In [4]:
# one hot encode outputs
y_train_cnn = to_categorical(y_train)
y_test_cnn = to_categorical(y_test)
num_classes = y_test_cnn.shape[1]

# reshape to be [samples][pixels][width][height]
X_train_cnn = X_train.reshape(X_train.shape[0], 28, 28, 1).astype('float32')
X_test_cnn = X_test.reshape(X_test.shape[0], 28, 28, 1).astype('float32')
s = X_train_cnn.shape
print(s, num_classes)

(1340, 28, 28, 1) 2


In [8]:
batch_size = 8
epochs = 12

# build the model
model = cnn_model()
# Fit the model
history = model.fit(X_train_cnn, y_train_cnn,
                    validation_data=(X_test_cnn, y_test_cnn),
                    epochs=epochs, batch_size=batch_size)
# Final evaluation of the model
scores = model.evaluate(X_test_cnn, y_test_cnn, verbose=0)
print('Final CNN accuracy: ', scores[1]*100, "%")

Train on 1340 samples, validate on 660 samples
Epoch 1/12
1340/1340 [==============================] - 1s 818us/step - loss: 0.4061 - accuracy: 0.8231 - val_loss: 0.3690 - val_accuracy: 0.8455
Epoch 2/12
1340/1340 [==============================] - 1s 659us/step - loss: 0.2955 - accuracy: 0.8813 - val_loss: 0.3068 - val_accuracy: 0.8803
Epoch 3/12
1340/1340 [==============================] - 1s 657us/step - loss: 0.2696 - accuracy: 0.8881 - val_loss: 0.2744 - val_accuracy: 0.8970
Epoch 4/12
1340/1340 [==============================] - 1s 635us/step - loss: 0.2193 - accuracy: 0.9157 - val_loss: 0.2574 - val_accuracy: 0.9061
Epoch 5/12
1340/1340 [==============================] - 1s 615us/step - loss: 0.1901 - accuracy: 0.9299 - val_loss: 0.2653 - val_accuracy: 0.8909
Epoch 6/12
1340/1340 [==============================] - 1s 615us/step - loss: 0.1726 - accuracy: 0.9336 - val_loss: 0.2591 - val_accuracy: 0.8924
Epoch 7/12
1340/1340 [==============================] - 1s 635us/step - loss:

In [6]:
grid = {'batch_size': [2, 4, 8, 12, 16, 18, 20, 22],
        'epochs': [2, 4, 8, 12, 16, 18, 20, 22]}
model = KerasClassifier(build_fn=cnn_model, verbose=0)
mlp_best_param = GridSearchCV(estimator=model,
                              param_grid=grid,
                              n_jobs=-1, verbose=3,
                              cv=5)
mlp_best_param.fit(X_train_cnn,y_train_cnn)
print(mlp_best_param.best_score_)
print(mlp_best_param.best_params_)

Fitting 3 folds for each of 64 candidates, totalling 192 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 112 tasks      | elapsed:  8.4min
[Parallel(n_jobs=-1)]: Done 192 out of 192 | elapsed: 13.1min finished


AttributeError: 'KerasClassifier' object has no attribute 'evaluate'

In [7]:
print(mlp_best_param.best_score_)
print(mlp_best_param.best_params_)

0.917154053846995
{'batch_size': 8, 'epochs': 22}
